spring:
  application:
    name: tradeflow

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: tradeflow-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.tradeflow.*"

  data:
    cassandra:
      schema-action: CREATE_IF_NOT_EXISTS

  cassandra:
    contact-points: localhost
    port: 9042
    local-datacenter: datacenter1
    keyspace-name: tradeflow
    schema-action: CREATE_IF_NOT_EXISTS

server:
  port: 8080

tradeflow:
  kafka:
    topic: trade-events